### ISSUE TITLE
Unable to run AASX server

### ISSUE THREAD

**Issue by AbiGithub91** [admin-shell-io/aasx-server#102]
Hi Team,

I am facing problem with running the application. Getting Uncaught SyntaxError: Unexpected token '}'
![aasxServerError](https://user-images.githubusercontent.com/33938064/154922552-02fac698-274f-4c5f-8c80-733135886f64.PNG)

**Comment by br-iosb** [comment]
Can you provide more information?
How did you start the Server? (Arguments, Environment, ...)
When does error occur?

**Comment by AbiGithub91** [comment]
Initially I followed the instructions in the Readme.md file and I tried executing the  AasxServerWindows>startForDemo.bat but got the following error:

![batFileError](https://user-images.githubusercontent.com/33938064/155283464-540b055b-5c0f-4af1-89f9-f670172f205b.PNG)

Later imported the solution in visual studio and built the AasxServerBlazor application and ran it and got the following error:

![consoleErrorAAsx](https://user-images.githubusercontent.com/33938064/155283678-dce4e1a7-9cd5-4cc8-b2f5-d0df94f90a4c.PNG)

Please tell me how to run the application and the right arguments to pass. I tried to run this in Windows Machine.

**Comment by AbiGithub91** [comment]
I downloaded and used the latest alpha version of AasxServerBlazor and its working but the core and windows version of AasxServer is not working.
