### ISSUE TITLE
The docker image doesn't expose the web UI 

### ISSUE THREAD

**Issue by emildinchev** [admin-shell-io/aasx-server#115]
Hi,
I'm following your description in the README.md how to start the Blazor server, using:
docker run -p 51000:51310 -p 51001:5001 adminshellio/aasx-server-blazor-for-demo

The REST server is working, but the blazor Web UI is not working.
In the corresponding Dockerfile, the exposed ports are 51310 and 51210.

Can you please check and give me some advice how to continue?

Best regards,
Emil

**Comment by NunoSav** [comment]
When running the blazor image the following warning is thrown:
```
Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to http://localhost:5001 on the IPv6 loopback interface: 'Cannot assign requested address'.
```

Whatever causes this needs fixing.

**Comment by br-iosb** [comment]
The warning mentioned by @NunoSav seems to be a .net core + docker specific issue.
You might try this workaround: https://stackoverflow.com/questions/59657499/unable-to-bind-to-http-localhost5000-on-the-ipv6-loopback-interface-cannot

**Comment by EmilAlipiev** [comment]
how does rest server working for you? I am trying to run it on Mac but I cannot reach using Localhost with 51310. is there any trick about it?

**Comment by juileetikekar** [comment]
Hi @EmilAlipiev,

Are you using the latest image/code? If yes, please try the port 5001, for the Blazor UI as well as the REST APIs. You can also access the swagger UI at the same port with "http://localhost:5001/swagger/index.html".

The port 51310 is no more supported in the latest version. Please refere the documentation at "https://github.com/admin-shell-io/aasx-server" for more information.
