### ISSUE TITLE
How to Update Property from ExampleMotor via PUT

### ISSUE THREAD

**Issue by vChavezB** [admin-shell-io/aasx-server#132]
I am trying to check how to update properties via the HTTP/REST API but I have not been able to do it properly.

I tried the following PUT request to update the `OperationalData `submodel property `RotationSpeed` but it did not work. 

### Request URL

http://localhost:51310/aas/ExampleMotor/submodels/OperationalData/elements/RotationSpeed

### Payload

```json
{
    "value": "1234"
}
```

### Response
```txt
Matching SubmodelElement in Submodel OperationalData is not suitable to add childs.
```

**Comment by juileetikekar** [comment]
Hi @vChavezB ,

Could you please use Asp.Net core APIs from the latest binaries, as mentioned in the GurHub issue [https://github.com/admin-shell-io/aasx-server/issues/130](url).

The new corresponding API (with Asp.Net ) to your request (i.e., Updating SubmodelElement "Property") is "http://localhost:5001/submodels/{Base64Url Encoded Submodel Identifier}/submodel/submodel-elements/RotationSpeed"

You will also find the swagger documentation of these API on: http://<Host_Name>:5001/swagger/index.html

**Comment by vChavezB** [comment]
Thanks for the info. Just as a reference here is how you can update the property from the motor example

PUT request endpoint: `http://localhost:5001/submodels/aHR0cDovL2k0MC5jdXN0b21lci5jb20vaW5zdGFuY2UvMS8xL0FDNjlCMUNCNDRGMDc5MzU/submodel/submodel-elements/RotationSpeed`

Payload 
```json
{
  "value": "1423",
  "valueId": null,
  "semanticId": {
    "keys": [
      {
        "type": "ConceptDescription",
        "local": true,
        "value": "http://customer.com/cd//1/1/18EBD56F6B43D895",
        "index": 0,
        "idType": "IRI"
      }
    ]
  },
  "constraints": [],
  "hasDataSpecification": [],
  "idShort": "RotationSpeed",
  "category": "VARIABLE",
  "modelType": {
    "name": "Property"
  },
  "valueType": {
    "dataObjectType": {
      "name": "integer"
    }
  },
  "kind": "Instance",
  "descriptions": null
}
``
