### ISSUE TITLE
Anymore .NET 3.1 supported

### ISSUE THREAD

**Issue by woohyuns123** [admin-shell-io/aasx-server#160]
https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual

Could you support me with dotnet version 6 or 7?

thx

**Comment by juileetikekar** [comment]
Hi @woohyuns123,

Please use the branch "[masterV3](https://github.com/admin-shell-io/aasx-server/tree/masterV3)", which is based on .NET6.
