### ISSUE TITLE
Restart docker container to view the latest aasx packages?

### ISSUE THREAD

**Issue by waleedshabbir1** [admin-shell-io/aasx-server#161]
Hello,
When I copy AASX packages into the aasxs directory of docker container I have to restart the docker container to see the packages listed on the 
http://localhost:51310/server/listaas 

Is this normal behavior or a bug?

**Comment by juileetikekar** [comment]
Hi @waleedshabbir1 ,

yes, this is the current behavior of the AASXServer. 

If the use case is to upload the AASXPackage to the AASXServer at runtime, then you can use REST-API to upload a new package. Please refer below GitHub issue for more details:
 https://github.com/admin-shell-io/aasx-server/issues/130
