### ISSUE TITLE
Operation without inputs or outputs cannot be created via REST API

### ISSUE THREAD

**Issue by HansG89** [admin-shell-io/aasx-server#170]
Branch: `masterV3`

At the moment it is not possible to create an operation that does not have inputs our outputs.

This can be fixed by adding a null check just before the `foreach` loops in 

https://github.com/admin-shell-io/aasx-server/blob/3abf7f1817bf5118293e1b2b7daddb864b1fac71/src/AasxServerStandardBib/Extenstions/ExtendIReferable.cs#L83

and 

https://github.com/admin-shell-io/aasx-server/blob/3abf7f1817bf5118293e1b2b7daddb864b1fac71/src/AasxServerStandardBib/Extenstions/ExtendIReferable.cs#L88

and 

https://github.com/admin-shell-io/aasx-server/blob/3abf7f1817bf5118293e1b2b7daddb864b1fac71/src/AasxServerStandardBib/Extenstions/ExtendIReferable.cs#L93

**Comment by juileetikekar** [comment]
Hi @HansG89,

Thank you for raising the issue. The null checks have already been added in the latest code( "main" branch).
