### ISSUE TITLE
How to PUT an Aasx File on Server by REST API?

### ISSUE THREAD

**Issue by zht120kg** [admin-shell-io/aasx-server#173]
![image](https://github.com/admin-shell-io/aasx-server/assets/100340309/d820a8f0-37e7-4d6f-9ccf-ec0d99dca723)
When I try to PUT an Aasx File to replace the Example Motor, I got this.
I'm confused about what form the http body should be?
Thank you.
Error Message:
`The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.`

**Comment by aorzelskiGH** [comment]
File is multipart. In Postman you need to use form data and then list the parameters. For file, select your file.
See /swagger in server.
