### ISSUE TITLE
Upload thumbnail to Asset Information API endpoint is missing

### ISSUE THREAD

**Issue by HansG89** [admin-shell-io/aasx-server#184]
Currently the API endpoint PUT `/shells/{aasIdentifier}/asset-information/thumbnail` is missing in `AssetAdministrationShellRepository` controller in the latest release.

**Comment by juileetikekar** [comment]
Hi @HansG89,

Thank you for raising the issue.

The issue has been fixed.

**Comment by EmilAlipiev** [comment]
it will be always nice if you can attached the commit or PR that fixes issues. Although it says fixed, it doesnt work for me. Always throwing exception even using through Swagger.
