### ISSUE TITLE
Typo in route of upload attachment to submodel element endpoint

### ISSUE THREAD

**Issue by HansG89** [admin-shell-io/aasx-server#185]
In the latest release there is a typo in the route of the endpoint that uploads attachments to submodel elements in `SubmodelRepositoryAPI` controller.
It should be `submodels/{submodelId}/submodel-elements/{idShortPath}/attachment` but currently it is `submodels/{submodelId}/submodelelements/{idShortPath}/attachment` which is not conformant with the standard.

**Comment by juileetikekar** [comment]
Hi @HansG89 ,

Thank you for raising the issue. The issue has been fixed. The changes can be found in "main" branch.
