### ISSUE TITLE
Crash if the statements object is null

### ISSUE THREAD

**Issue by EmilAlipiev** [admin-shell-io/aasx-server#188]
As shown below server crashes if the statements are null. I have tested using Demo Box samples from here http://www.admin-shell-io.com/samples/

<img width="812" alt="image" src="https://github.com/admin-shell-io/aasx-server/assets/10422347/e70ea1ff-22b8-49f5-a52a-a4c91274f849">

**Comment by juileetikekar** [comment]
Hi @EmilAlipiev,

Thank you for raising the issue. The issue has been fixed in "main" branch.
