### ISSUE TITLE
Docker image and source code not same

### ISSUE THREAD

**Issue by EmilAlipiev** [admin-shell-io/aasx-server#191]
I would like to ask how often is docker images are refreshed. Because we have found out that there is a big discrepancy between docker latest image and main source code. When i tried to create a submodel using docker image running on my mac, it was working fine but exact the same client code, I have executed downloading the latest main source code and running in VS 2022, it threw an exception. 
So obviously docker image was not up-to-date.

**Comment by juileetikekar** [comment]
Hi @EmilAlipiev,

Could you please confirm if you are using the "main" tag from the docker hub (screenshot in the end)?

![image](https://github.com/admin-shell-io/aasx-server/assets/99317579/1183a848-46d6-4225-9f73-740e3c7af49a)

**Comment by EmilAlipiev** [comment]
Hi @juileetikekar, good point. I have used the link on the read.met directly.
