### ISSUE TITLE
GET /shell-descriptors/{aasIdentifier}/submodel-descriptors/{submodelIdentifier} returns 204 without content

### ISSUE THREAD

**Issue by EmilAlipiev** [admin-shell-io/aasx-server#204]
Get query returns 204 without any content which makes no sense? it should return error if not found. 

![image](https://github.com/admin-shell-io/aasx-server/assets/10422347/84ca3413-c06b-4543-b628-fd9c5d971371)

**Comment by juileetikekar** [comment]
Hi @EmilAlipiev,

The API is not implemented yet. However, we have changed the return message from 204 to the exception "Not implemented".
