### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by simogalpa** [admin-shell-io/aasx-server#49]
It is possible to add some documentation on the REST API provided with the server if present? 

Some minimal documentation can be founded on the previous repository but not detailed enough to be really useful.

**Comment by mristin** [comment]
Hi @simogalpa ,
We could write OpenAPI 3 spec and provide it under /openapi3 route. While we do not use a library that directly binds with the spec, we could at least write a component test to test all the routes with the examples.

Would that work for you?

**Comment by simogalpa** [comment]
Hi, @mristin I think this solution will work perfectly!

Thank you!

**Comment by mristin** [comment]
Please give me a coule of days. @MichaelHoffmeisterFesto any considerations/doubts?

**Comment by mristin** [comment]
@MichaelHoffmeisterFesto should we put the link in the Readme? IMO, it belongs to the user manual (*i.e.* main Readme for the time being) and I wouldn't put it in the documentation for developers.

**Comment by leoneversberg** [comment]
Hi,
are there any updates on the REST API?
I don't know how to update properties with PUT, even some minimal examples would be helpful!

**Comment by BirgitBoss** [comment]
The REST API is now published: https://industrialdigitaltwin.org/wp-content/uploads/2021/11/Details_of_the_Asset_Administration_Shell_Part_2_V1.pdf

**Comment by juileetikekar** [comment]
Hi All, the Aasx-Server is upgraded with new REST-API with ASP.NET. It is also supported with Swagger-Documentaion. The details as below:

Server Endpoint: https://registry.h2894164.stratoserver.net/
Swagger Documentation: https://swagger.h2894164.stratoserver.net/swagger/index.html
API example => Get All Asset Administration Shells: https://swagger.h2894164.stratoserver.net/shells
For more details: https://industrialdigitaltwin.org/wp-content/uploads/2021/11/Details_of_the_Asset_Administration_Shell_Part_2_V1.pdf
