### ISSUE TITLE
Bill of material and Reference 

### ISSUE THREAD

**Issue by simogalpa** [admin-shell-io/aasx-server#50]
If the submodel Bill of material is created and populated with Self managed Entities the relation between the Element in the Bill of material Submodel and the referred AAS should be managed by the server. 

In this way by clicking on the reference the corresponding AAS should open and the navigation between them for the user is simplified. 

![Immagine 2020-11-05 171750](https://user-images.githubusercontent.com/2984297/98266678-e140cb80-1f8a-11eb-9b8c-e0baab3a242a.png)

**Comment by BirgitBoss** [comment]
This is a nice feature, however it assumes that the endpoint of the AAS in the BOM is available (the id is just a logical id). So it is not just navigating but1) asking a registry for the endpoint and 2) then redirecting to the new endpoint.
Only in the case that all AAS are on the same server this might be simplified.

**Comment by juileetikekar** [comment]
Hi @simogalpa,

we would like to suggest you to have a look at IDTA's submodel template "[Hierarchical Structures Enabling BoM](https://industrialdigitaltwin.org/content-hub/teilmodelle)" in this regard.
