### ISSUE TITLE
Allow traversal of entities

### ISSUE THREAD

**Issue by mkollenstart** [admin-shell-io/aasx-server#73]
Currently only SubmodelElementCollections and Operation can be traversed in the HTTP API, but the Entity statements should also be able to traverse easily in the API.

I will link an pull request with an implementation of this feature

**Comment by juileetikekar** [comment]
This issue has been fixed in the new REST API support with ASP.NET.
The new REST endpoint is : http://<Host_Name>:5001/
Swagger documentation for these APIs can be found at : http://<Host_Name>:5001/swagger/index.html
